version: '3.9'

services:
  devops-website:
    container_name: website
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/usr/share/nginx/html:ro
